routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [App\Http\Controllers\PhotosController::class, 'index'])->name('index')->middleware('language');

Route::prefix('client')->middleware(['auth', 'language'])->name('client.')->group(function () {
    Route::resource('photos', \App\Http\Controllers\PhotosController::class)->only(['index', 'show', 'create', 'store', 'destroy']);
    Route::resource('users', \App\Http\Controllers\UsersController::class)->only(['show']);
    Route::resource('photos.comments', \App\Http\Controllers\CommentsController::class)->only(['store']);
//    Route::resource('authors', AuthorsController::class)->only(['index', 'show']);
//    Route::resource('books.comments', CommentsController::class)->only(['store']);
//    Route::resource('comments', CommentsController::class)->only(['edit', 'update', 'destroy']);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('language/{locale}', [\App\Http\Controllers\LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')->where('locale', 'en|ru');

app/Models/Photo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Photo extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'picture'];

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->latest();
    }

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/PhotosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Photo;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;

class PhotosController extends Controller
{

    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $photos = Photo::latest()->paginate(6);
        return view('client.photos.index', compact('photos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', Photo::class);
        return view('client.photos.create');
    }


    /**
     * @param Request $request
     * @return Application|RedirectResponse|Redirector
     * @throws AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('update', Photo::class);
        $data = $request->all();
        $file = $request->file('picture');
        $path = $file->store('photos_pictures', 'public');
        $data['picture'] = $path;

        $photo = new Photo($data);
        $photo->user()->associate($request->user());
        $photo->save();
        return redirect(route('client.photos.index'))->with('success', "$photo->title added successfully");
    }


    /**
     * @param Photo $photo
     * @return Application|Factory|View
     */
    public function show(Photo $photo)
    {
        return view('client.photos.show', compact('photo'));
    }

//    /**
//     * Show the form for editing the specified resource.
//     *
//     * @param  \App\Models\Photo  $photo
//     * @return \Illuminate\Http\Response
//     */
//    public function edit(Photo $photo)
//    {
//        return view('client.photos.edit', compact('photo'));
//    }
//
//    /**
//     * Update the specified resource in storage.
//     *
//     * @param  \Illuminate\Http\Request  $request
//     * @param  \App\Models\Photo  $photo
//     * @return \Illuminate\Http\Response
//     */
//    public function update(Request $request, Photo $photo)
//    {
//        //
//    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Photo $photo
     * @return Application|Redirector|RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Photo $photo)
    {
        $this->authorize('delete', Photo::class);
        $photo->delete();
        return redirect(route('client.photos.index'))->with('success', "$photo->title deleted successfully");
    }
}

resources/views/client/photos/create.blade.php
@extends('layouts.client')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <br>
                <h5>Create new photo</h5>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col">
                <form method="post" action="{{ route('client.photos.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="mb-3">
                        <label for="title">Caption:</label>
                        <input type="text" class="form-control" name="title" id="title" value="{{ old('title') }}"/>
                        @error('title')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <div class="mb-3">
                            <label class="form-control-file" for="custom-file">Image:</label>
                            <input type="file" class="form-control-file" name="picture" id="custom-file"/>
                        </div>
                        @error('picture')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <br>
                    <button class="btn btn-primary" type="submit">Create photo</button>
                    <br>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/client/photos/index.blade.php
@extends('layouts.client')

@section('content')
    <div class="container">
        <br>
        <div class="row">
            @foreach($photos as $photo)
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{asset('/storage/' . $photo->picture)}}" alt="{{$photo->picture}}">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{{route('client.photos.show', ['photo' => $photo])}}">{{$photo->title}}</a></h5>
                        <h5 class="card-title">By {{$photo->user->name}}</h5>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <div class="row justify-content-md-center p-5">

        <div class="col-md-auto">

            {{ $photos->links('pagination::bootstrap-4') }}

        </div>

    </div>

@endsection

resources/views/client/photos/show.blade.php
@extends('layouts.client')

@section('content')
    <div class="container">
        <br>
        <div class="row">
            <div class="col">
                <p>
                    <h3><b>{{$photo->title}}</b></h3>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p>
                        <img width="500" height="500" src="{{asset('/storage/' . $photo->picture)}}" alt="{{$photo->picture}}">
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p>
                    <b>"@lang('Photo By:') </b> {{$photo->user->name}}, {{$photo->created_at->diffForHumans()}}
                </p>
            </div>
        </div>
        <br>
        <form action="{{action([App\Http\Controllers\PhotosController::class, 'index'])}}">
            <button class="btn btn-primary">Назад</button>
        </form>
        <br>
        <br>
        <h3>@lang('Comments')</h3>
        @foreach($photo->comments as $comment)
            <p>@lang('By:') {{$comment->user->name}}, @lang('Score:') {{$comment->grade}}</p>
            <p>{{$comment->body}}</p>
            <hr>
        @endforeach
        @can('create', $comment)
        <div class="row">
            <div class="col">
                <form method="post" action="{{ route('client.photos.comments.store', ['photo' => $photo])}}">
                    @csrf
                    <input type="hidden" id="book_id" value="{{$photo->id}}">
                    <div class="mb-3">
                        <label for="body">Text:</label>
                        <input type="text" class="form-control" name="body" id="body" value="{{ old('body') }}"/>
                        @error('body')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="grade">Score</label>
                            <select name="grade" class="form-control" id="grade">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        @error('grade')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <br>
                    <button class="btn btn-primary" type="submit">Create comment</button>
                    <br>
                </form>
            </div>
    @endcan
@endsection