routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [App\Http\Controllers\PhotosController::class, 'index'])->name('index')->middleware('language');

Route::prefix('client')->middleware(['auth', 'language'])->name('client.')->group(function () {
    Route::resource('photos', \App\Http\Controllers\PhotosController::class)->only(['index', 'show', 'create', 'store', 'destroy']);
    Route::resource('users', \App\Http\Controllers\UsersController::class)->only(['show']);
    Route::resource('photos.comments', \App\Http\Controllers\CommentsController::class)->only(['store']);
//    Route::resource('authors', AuthorsController::class)->only(['index', 'show']);
//    Route::resource('books.comments', CommentsController::class)->only(['store']);
//    Route::resource('comments', CommentsController::class)->only(['edit', 'update', 'destroy']);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('language/{locale}', [\App\Http\Controllers\LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')->where('locale', 'en|ru');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return HasMany
     */
    public function photos(): HasMany
    {
        return $this->hasMany(Photo::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
//        $user = Auth::user();
        return view('client.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/client/users/show.blade.php
@extends('layouts.client')

@section('content')
    <div class="container">
        <br>
        <div class="row">
            <div class="col">
                <p>
                <h3><b>Profile</b> {{$user->name}}</h3>
                </p>
            </div>
        </div>
        <br>
        <form action="{{action([App\Http\Controllers\PhotosController::class, 'index'])}}">
            <button class="btn btn-primary">Назад</button>
        </form>

        <br>
        <b>My photos {{$user->name}}</b>
        <form action="{{action([App\Http\Controllers\PhotosController::class, 'create'])}}">
            <button class="btn btn-primary">Create new photo</button>
        </form>
        <br>
        <br>
        <div class="row">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Photo</th>
                    <th scope="col">Title</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($user->photos as $photo)
                    <tr>
                        <td>{{$photo->id}}</td>
                        <td>
                                <img width="100" height="100" src="{{asset('/storage/' . $photo->picture)}}" alt="{{$photo->picture}}">
                        </td>
                        <td>
                            <a href="{{route('client.photos.show', ['photo' => $photo])}}">
                                {{$photo->title}}
                            </a>
                        </td>
                        <td>
                            <form action="{{action([App\Http\Controllers\PhotosController::class, 'destroy'],
                                        ['photo'=> $photo])}}" method="post">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-sm btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
{{--        <div class="row">--}}
{{--            @foreach($user->photos as $photo)--}}
{{--                <div class="card" style="width: 18rem;">--}}
{{--                    <img class="card-img-top" src="{{asset('/storage/' . $photo->picture)}}" alt="{{$book->picture}}">--}}
{{--                    <div class="card-body">--}}
{{--                        <h5 class="card-title"><a href="{{route('client.books.show', ['book' => $book])}}">{{$book->title}}</a></h5>--}}
{{--                        <p class="card-text">--}}
{{--                            @if(!is_null($book->author))--}}
{{--                                Автор: <a href="{{route('client.authors.show', ['author' => $book->author])}}">{{$book->author->name}}</a>--}}
{{--                            @endif--}}
{{--                            <br>--}}
{{--                            @if(!is_null($book->genre))--}}
{{--                                Жанр: <a href="{{route('client.genres.show', ['genre' => $book->genre])}}">{{$book->genre->name}}</a>--}}
{{--                            @endif--}}
{{--                        </p>--}}
{{--                        <footer class="blockquote-footer">--}}
{{--                            Цена: {{number_format($book->price, 2)}}--}}
{{--                        </footer>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                --}}{{--                @endif--}}
{{--            @endforeach--}}
{{--        </div>--}}
    </div>

@endsection